services:
  transportation_db_postgres:
    image: 'postgres:16.4'
    container_name: "transportation-postgres"
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${TRANSPORTATION_PG_USER}
      POSTGRES_PASSWORD: ${TRANSPORTATION_PG_PASSWORD}
      POSTGRES_DB: ${TRANSPORTATION_PG_DATABASE}
    ports:
      - ${TRANSPORTATION_PG_PORT}:5432
#    volumes:
#      - postgres_data_transportation:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${TRANSPORTATION_PG_USER} -d ${TRANSPORTATION_PG_DATABASE} -p 5432"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - gruzowiki_network

  transportation_flyway:
    image: 'flyway/flyway:11.4'
    container_name: "transportation-flyway"
    env_file:
      - .env
    environment:
      FLYWAY_URL: jdbc:postgresql://transportation_db_postgres:5432/${TRANSPORTATION_PG_DATABASE}
      FLYWAY_USER: ${TRANSPORTATION_PG_USER}
      FLYWAY_PASSWORD: ${TRANSPORTATION_PG_PASSWORD}
    command:
      - migrate
    volumes:
      - ./db/pg/migrations:/flyway/sql
    depends_on:
      transportation_db_postgres:
        condition: service_started
        restart: true
    networks:
      - gruzowiki_network

  transportation_service:
    build:
      dockerfile: Dockerfile
    container_name: "transportation-service"
    env_file:
      - .env 
    environment:
      LOG_LEVEL: ${LOG_LEVEL}
      UPDATE_ADDRESS: ${UPDATE_ADDRESS}
      DSN: "user='${TRANSPORTATION_PG_USER}' password='${TRANSPORTATION_PG_PASSWORD}' host='${TRANSPORTATION_PG_HOST}' port=${TRANSPORTATION_PG_PORT} dbname='${TRANSPORTATION_PG_DATABASE}' sslmode=disable"
    ports:
       - "${TRANSPORTATION_SERVICE_PORT}:8075"
    depends_on:
      transportation_db_postgres:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - gruzowiki_network

volumes:
  postgres_data_transportation:

networks:
  gruzowiki_network:
    name: "gruzowiki-network"
    driver: bridge
    external: true