services:
  transportation_db_postgres:
    image: 'postgres:16.4'
    container_name: "transportation-postgres"
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${TRANSPORTATION_PG_USER}
      POSTGRES_PASSWORD: ${TRANSPORTATION_PG_PASSWORD}
      POSTGRES_DB: ${TRANSPORTATION_PG_DATABASE}
    ports:
      - "${TRANSPORTATION_PG_PORT}:5432"
    networks:
      - gruzowiki_network

  transportation_flyway:
    image: 'flyway/flyway:11.4'
    container_name: "transportation-flyway"
    env_file:
      - .env
    environment:
      FLYWAY_URL: jdbc:postgresql://transportation_db_postgres:5432/${TRANSPORTATION_PG_DATABASE}
      FLYWAY_USER: ${TRANSPORTATION_PG_USER}
      FLYWAY_PASSWORD: ${TRANSPORTATION_PG_PASSWORD}
    command:
      - migrate
    volumes:
      - ./migrations:/flyway/sql
    depends_on:
      transportation_db_postgres:
        condition: service_started
        restart: true
    networks:
      - gruzowiki_network

#  transportation_service:
#    build:
#      dockerfile: Dockerfile
#    container_name: "transportation-service"
#    env_file:
#      - .env
#    environment:
#      TRANSPORTATION_PG_HOST: transportation_db_postgres
#      TRANSPORTATION_PG_PORT: 5432
#      PUBLIC_KEY_FILE_PATH: keys/public/jws-public.pem
#      PRIVATE_KEY_FILE_PATH: keys/private/jws-private.pem
#    ports:
#      - "${TRANSPORTATION_SERVICE_PORT}:8080"
#    volumes:
#      - ./src/main/resources/keys/public:/keys/public
#      - ./src/main/resources/keys/private:/keys/private
#    depends_on:
#      - transportation_db_postgres
#    networks:
#      - gruzowiki_network

networks:
  gruzowiki_network:
    name: "gruzowiki-network"
    driver: bridge
    external: true