-- отправитель
create table consigners(
    id int primary key generated by default as identity
);

-- грузоперевозчик
create table carriers(
    id int primary key,
    driver_category varchar(50)
);

create table cars(
    id int primary key generated by default as identity,
    type varchar(10),
    length int,
    width int,
    height int,
    max_weight int,
    number varchar(10) unique,
    owner int references carriers(id)
);

create table trips(
    id uuid primary key default gen_random_uuid(),
    from_station bigint,
    to_station bigint,
    started_at timestamp,
    calculate_end_at timestamp,
    actual_end_at timestamp,
    price decimal(10, 2),
    status varchar(50),
    carrier int references carriers(id),
    car int references cars(id)
);

create table stations_sequences(
    trip_id uuid references trips(id),
    station_id bigint,
    distance int,
    order_num int,
    primary key (trip_id, station_id)
);

-- получатель
create table recipients(
    id int primary key generated by default as identity,
    first_name varchar(100),
    second_name varchar(100),
    third_name varchar(100),
    phone int unique,
    passport_series int,
    passport_number int,
    unique (passport_series, passport_number)
);

create table requests(
    id uuid primary key default gen_random_uuid(),
    consigner_id int references consigners(id),
    recipient_id int references recipients(id),
    created_at timestamp,
    deadline timestamp,
    trip_id uuid references trips(id),
    from_station bigint,
    to_station bigint,
    price decimal(10, 2),
    status varchar(50)
);

create table cargo_types(
    id int primary key generated by default as identity,
    type varchar(50)
);
insert into cargo_types (type) values ('type1'), ('type2');

create table cargo(
    id uuid primary key default gen_random_uuid(),
    length int,
    width int,
    height int,
    weight int,
    cargo_type int references cargo_types(id) default 1,
    worth decimal(10, 2),
    request_id uuid references requests(id)
);