-- отправитель
create table consigners(
    id int primary key
);

-- грузоперевозчик
create table carriers(
    id int primary key,
    driver_category varchar(50)
);

create table cars(
    id int primary key generated by default as identity,
    type varchar(10),
    length int,
    width int,
    height int,
    max_weight int,
    number varchar(10) unique,
    owner int references carriers(id)
);

create table stations(
    id uuid primary key default gen_random_uuid(),
    address varchar(200),
    lat float8,
    lon float8
);

create table trips(
    id uuid primary key default gen_random_uuid(),
    route_id uuid,
    from_station uuid references stations(id),
    to_station uuid references stations(id),
    started_at bigint,
    calculate_end_at bigint,
    actual_end_at bigint,
    price decimal(10, 2),
    status varchar(50),
    carrier int references carriers(id),
    car int references cars(id)
);

-- получатель
create table recipients(
    id int primary key generated by default as identity,
    first_name varchar(100),
    second_name varchar(100),
    third_name varchar(100),
    phone varchar(15) unique,
    email varchar(100) unique
);

create table cargo_requests(
    id uuid primary key default gen_random_uuid(),
    consigner_id int references consigners(id),
    recipient_id int references recipients(id),
    from_station uuid references stations(id),
    to_station uuid references stations(id),
    created_at bigint,
    deadline bigint,
    route_id uuid,
    trip_id uuid references trips(id),
    price decimal(10, 2),
    status varchar(50)
);

create table cargo_types(
    id int primary key generated by default as identity,
    type varchar(50),
    fragile boolean
);
insert into cargo_types (type, fragile) values ('type1', false), ('fragile', true);

create table cargo(
    id uuid primary key default gen_random_uuid(),
    length int,
    width int,
    height int,
    weight int,
    cargo_type int references cargo_types(id) default 1,
    worth decimal(10, 2),
    request_id uuid references cargo_requests(id)
);

insert into carriers(id, driver_category) values (2, 'cat1');

insert into carriers(id, driver_category) values (1, 'b');

insert into consigners(id) values (1);
insert into recipients(id, first_name, second_name, third_name, phone, email)
values (1, 'fn', 'sn', 'tn', '1234', 'email');