// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package pg

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Car struct {
	ID        int32
	Type      pgtype.Text
	Length    pgtype.Int4
	Width     pgtype.Int4
	Height    pgtype.Int4
	MaxWeight pgtype.Int4
	Number    pgtype.Text
	Owner     pgtype.Int4
}

type Cargo struct {
	ID        pgtype.UUID
	Length    pgtype.Int4
	Width     pgtype.Int4
	Height    pgtype.Int4
	Weight    pgtype.Int4
	CargoType pgtype.Int4
	Worth     pgtype.Numeric
	RequestID pgtype.UUID
}

type CargoType struct {
	ID   int32
	Type pgtype.Text
}

type Carrier struct {
	ID             int32
	DriverCategory pgtype.Text
}

type Consigner struct {
	ID int32
}

type Recipient struct {
	ID             int32
	FirstName      pgtype.Text
	SecondName     pgtype.Text
	ThirdName      pgtype.Text
	Phone          pgtype.Int4
	PassportSeries pgtype.Int4
	PassportNumber pgtype.Int4
}

type Request struct {
	ID          pgtype.UUID
	ConsignerID pgtype.Int4
	RecipientID pgtype.Int4
	CreatedAt   pgtype.Timestamp
	Deadline    pgtype.Timestamp
	TripID      pgtype.UUID
	FromStation pgtype.Int8
	ToStation   pgtype.Int8
	Price       pgtype.Numeric
	Status      pgtype.Text
}

type StationsSequence struct {
	TripID    pgtype.UUID
	StationID int64
	Distance  pgtype.Int4
	OrderNum  pgtype.Int4
}

type Trip struct {
	ID             pgtype.UUID
	FromStation    pgtype.Int8
	ToStation      pgtype.Int8
	StartedAt      pgtype.Timestamp
	CalculateEndAt pgtype.Timestamp
	ActualEndAt    pgtype.Timestamp
	Price          pgtype.Numeric
	Status         pgtype.Text
	Carrier        pgtype.Int4
	Car            pgtype.Int4
}
