// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package pg

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Car struct {
	ID        int32
	Type      pgtype.Text
	Length    pgtype.Int4
	Width     pgtype.Int4
	Height    pgtype.Int4
	MaxWeight pgtype.Int4
	Number    pgtype.Text
	Owner     pgtype.Int4
}

type Cargo struct {
	ID        pgtype.UUID
	Length    pgtype.Int4
	Width     pgtype.Int4
	Height    pgtype.Int4
	Weight    pgtype.Int4
	CargoType pgtype.Int4
	Worth     pgtype.Numeric
	RequestID pgtype.UUID
}

type CargoRequest struct {
	ID          pgtype.UUID
	ConsignerID pgtype.Int4
	RecipientID pgtype.Int4
	FromStation pgtype.UUID
	ToStation   pgtype.UUID
	CreatedAt   pgtype.Int8
	Deadline    pgtype.Int8
	RouteID     pgtype.UUID
	TripID      pgtype.UUID
	Price       pgtype.Numeric
	Status      pgtype.Text
}

type CargoType struct {
	ID      int32
	Type    pgtype.Text
	Fragile pgtype.Bool
}

type Carrier struct {
	ID             int32
	DriverCategory pgtype.Text
}

type Consigner struct {
	ID int32
}

type Recipient struct {
	ID         int32
	FirstName  pgtype.Text
	SecondName pgtype.Text
	ThirdName  pgtype.Text
	Phone      pgtype.Text
	Email      pgtype.Text
}

type Trip struct {
	ID             pgtype.UUID
	RouteID        pgtype.UUID
	FromStation    pgtype.UUID
	ToStation      pgtype.UUID
	StartedAt      pgtype.Int8
	CalculateEndAt pgtype.Int8
	ActualEndAt    pgtype.Int8
	Price          pgtype.Numeric
	Status         pgtype.Text
	Carrier        pgtype.Int4
	Car            pgtype.Int4
}
