// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package pg

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createCar = `-- name: CreateCar :one
INSERT INTO cars (
    type, length, width, height, max_weight, number, owner
) VALUES (
    $1, $2, $3, $4, $5, $6, $7
) RETURNING id
`

type CreateCarParams struct {
	Type      pgtype.Text
	Length    pgtype.Int4
	Width     pgtype.Int4
	Height    pgtype.Int4
	MaxWeight pgtype.Int4
	Number    pgtype.Text
	Owner     pgtype.Int4
}

func (q *Queries) CreateCar(ctx context.Context, arg CreateCarParams) (int32, error) {
	row := q.db.QueryRow(ctx, createCar,
		arg.Type,
		arg.Length,
		arg.Width,
		arg.Height,
		arg.MaxWeight,
		arg.Number,
		arg.Owner,
	)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const createCargo = `-- name: CreateCargo :one
INSERT INTO cargo (length, width, height, weight, cargo_type, worth, request_id)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id
`

type CreateCargoParams struct {
	Length    pgtype.Int4
	Width     pgtype.Int4
	Height    pgtype.Int4
	Weight    pgtype.Int4
	CargoType pgtype.Int4
	Worth     pgtype.Numeric
	RequestID pgtype.UUID
}

func (q *Queries) CreateCargo(ctx context.Context, arg CreateCargoParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, createCargo,
		arg.Length,
		arg.Width,
		arg.Height,
		arg.Weight,
		arg.CargoType,
		arg.Worth,
		arg.RequestID,
	)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const createCarrier = `-- name: CreateCarrier :one
INSERT INTO carriers (id, driver_category) VALUES ($1, $2) RETURNING id
`

type CreateCarrierParams struct {
	ID             int32
	DriverCategory pgtype.Text
}

func (q *Queries) CreateCarrier(ctx context.Context, arg CreateCarrierParams) (int32, error) {
	row := q.db.QueryRow(ctx, createCarrier, arg.ID, arg.DriverCategory)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const createRecipient = `-- name: CreateRecipient :one
INSERT INTO recipients (first_name, second_name, third_name, phone, email)
VALUES ($1, $2, $3, $4, $5)
RETURNING id
`

type CreateRecipientParams struct {
	FirstName  pgtype.Text
	SecondName pgtype.Text
	ThirdName  pgtype.Text
	Phone      pgtype.Text
	Email      pgtype.Text
}

func (q *Queries) CreateRecipient(ctx context.Context, arg CreateRecipientParams) (int32, error) {
	row := q.db.QueryRow(ctx, createRecipient,
		arg.FirstName,
		arg.SecondName,
		arg.ThirdName,
		arg.Phone,
		arg.Email,
	)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const deleteCar = `-- name: DeleteCar :exec
DELETE FROM cars WHERE id = $1
`

func (q *Queries) DeleteCar(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteCar, id)
	return err
}

const deleteCarrier = `-- name: DeleteCarrier :exec
DELETE FROM carriers WHERE id = $1
`

func (q *Queries) DeleteCarrier(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteCarrier, id)
	return err
}

const deleteRecipient = `-- name: DeleteRecipient :exec
DELETE FROM recipients WHERE id = $1
`

func (q *Queries) DeleteRecipient(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteRecipient, id)
	return err
}

const getCar = `-- name: GetCar :one
SELECT 
    id, 
    type, 
    length, 
    width, 
    height, 
    max_weight, 
    number, 
    owner 
FROM cars 
WHERE id = $1
`

func (q *Queries) GetCar(ctx context.Context, id int32) (Car, error) {
	row := q.db.QueryRow(ctx, getCar, id)
	var i Car
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Length,
		&i.Width,
		&i.Height,
		&i.MaxWeight,
		&i.Number,
		&i.Owner,
	)
	return i, err
}

const getCargoRequest = `-- name: GetCargoRequest :many
select id, consigner_id, recipient_id, from_station, to_station, created_at, deadline, route_id, trip_id, price, status, receive_code from cargo_requests where id = $1
`

func (q *Queries) GetCargoRequest(ctx context.Context, id pgtype.UUID) ([]CargoRequest, error) {
	rows, err := q.db.Query(ctx, getCargoRequest, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CargoRequest
	for rows.Next() {
		var i CargoRequest
		if err := rows.Scan(
			&i.ID,
			&i.ConsignerID,
			&i.RecipientID,
			&i.FromStation,
			&i.ToStation,
			&i.CreatedAt,
			&i.Deadline,
			&i.RouteID,
			&i.TripID,
			&i.Price,
			&i.Status,
			&i.ReceiveCode,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCargoTypes = `-- name: GetCargoTypes :many
SELECT id, type, fragile FROM cargo_types
`

func (q *Queries) GetCargoTypes(ctx context.Context) ([]CargoType, error) {
	rows, err := q.db.Query(ctx, getCargoTypes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CargoType
	for rows.Next() {
		var i CargoType
		if err := rows.Scan(&i.ID, &i.Type, &i.Fragile); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCarrier = `-- name: GetCarrier :one
SELECT id, driver_category FROM carriers WHERE id = $1
`

func (q *Queries) GetCarrier(ctx context.Context, id int32) (Carrier, error) {
	row := q.db.QueryRow(ctx, getCarrier, id)
	var i Carrier
	err := row.Scan(&i.ID, &i.DriverCategory)
	return i, err
}

const getRecipient = `-- name: GetRecipient :one
SELECT id, first_name, second_name, third_name, phone, email
FROM recipients
WHERE id = $1
`

func (q *Queries) GetRecipient(ctx context.Context, id int32) (Recipient, error) {
	row := q.db.QueryRow(ctx, getRecipient, id)
	var i Recipient
	err := row.Scan(
		&i.ID,
		&i.FirstName,
		&i.SecondName,
		&i.ThirdName,
		&i.Phone,
		&i.Email,
	)
	return i, err
}

const getSuitableTripsForCargoRequest = `-- name: GetSuitableTripsForCargoRequest :many
SELECT 
    t.route_id
FROM cargo_requests cr
JOIN cargo ON cargo.request_id = cr.id
JOIN cargo_types ct ON cargo.cargo_type = ct.id
CROSS JOIN trips t
JOIN cars c ON t.car = c.id
WHERE cr.id = $1
  AND cr.deadline >= t.calculate_end_at
  AND cargo.weight <= c.max_weight
  AND cargo.length <= c.length
  AND cargo.width <= c.width
  AND cargo.height <= c.height
`

func (q *Queries) GetSuitableTripsForCargoRequest(ctx context.Context, id pgtype.UUID) ([]pgtype.UUID, error) {
	rows, err := q.db.Query(ctx, getSuitableTripsForCargoRequest, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []pgtype.UUID
	for rows.Next() {
		var route_id pgtype.UUID
		if err := rows.Scan(&route_id); err != nil {
			return nil, err
		}
		items = append(items, route_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTripByCargoRequest = `-- name: GetTripByCargoRequest :one
SELECT t.id, t.route_id, t.from_station, t.to_station, t.started_at, t.calculate_end_at, t.actual_end_at, t.price, t.status, t.carrier, t.car
FROM trips t
JOIN cargo_requests c ON c.trip_id = t.id
WHERE c.id = $1
`

func (q *Queries) GetTripByCargoRequest(ctx context.Context, id pgtype.UUID) (Trip, error) {
	row := q.db.QueryRow(ctx, getTripByCargoRequest, id)
	var i Trip
	err := row.Scan(
		&i.ID,
		&i.RouteID,
		&i.FromStation,
		&i.ToStation,
		&i.StartedAt,
		&i.CalculateEndAt,
		&i.ActualEndAt,
		&i.Price,
		&i.Status,
		&i.Carrier,
		&i.Car,
	)
	return i, err
}

const getTripsByIDsWithPagination = `-- name: GetTripsByIDsWithPagination :many
SELECT 
    t.id,
    t.started_at,
    t.calculate_end_at,
    t.actual_end_at,
    t.price,
    t.status,
    t.carrier as carrier_id,
    t.car as car_id,
    fs.address as from_address,
    fs.lat as from_lat,
    fs.lon as from_lon,
    ts.address as to_address,
    ts.lat as to_lat,
    ts.lon as to_lon
FROM trips t
JOIN stations fs ON t.from_station = fs.id
JOIN stations ts ON t.to_station = ts.id
WHERE t.id = ANY($1::uuid[])
LIMIT $2 OFFSET $3
`

type GetTripsByIDsWithPaginationParams struct {
	Column1 []pgtype.UUID
	Limit   int32
	Offset  int32
}

type GetTripsByIDsWithPaginationRow struct {
	ID             pgtype.UUID
	StartedAt      pgtype.Int8
	CalculateEndAt pgtype.Int8
	ActualEndAt    pgtype.Int8
	Price          pgtype.Numeric
	Status         pgtype.Text
	CarrierID      pgtype.Int4
	CarID          pgtype.Int4
	FromAddress    pgtype.Text
	FromLat        pgtype.Float8
	FromLon        pgtype.Float8
	ToAddress      pgtype.Text
	ToLat          pgtype.Float8
	ToLon          pgtype.Float8
}

func (q *Queries) GetTripsByIDsWithPagination(ctx context.Context, arg GetTripsByIDsWithPaginationParams) ([]GetTripsByIDsWithPaginationRow, error) {
	rows, err := q.db.Query(ctx, getTripsByIDsWithPagination, arg.Column1, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetTripsByIDsWithPaginationRow
	for rows.Next() {
		var i GetTripsByIDsWithPaginationRow
		if err := rows.Scan(
			&i.ID,
			&i.StartedAt,
			&i.CalculateEndAt,
			&i.ActualEndAt,
			&i.Price,
			&i.Status,
			&i.CarrierID,
			&i.CarID,
			&i.FromAddress,
			&i.FromLat,
			&i.FromLon,
			&i.ToAddress,
			&i.ToLat,
			&i.ToLon,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertCargoRequest = `-- name: InsertCargoRequest :one
insert into cargo_requests (id, consigner_id, recipient_id, from_station, to_station, created_at, deadline, route_id, trip_id, price, status, receive_code)
values ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12) returning id
`

type InsertCargoRequestParams struct {
	ID          pgtype.UUID
	ConsignerID pgtype.Int4
	RecipientID pgtype.Int4
	FromStation pgtype.UUID
	ToStation   pgtype.UUID
	CreatedAt   pgtype.Int8
	Deadline    pgtype.Int8
	RouteID     pgtype.UUID
	TripID      pgtype.UUID
	Price       pgtype.Numeric
	Status      pgtype.Text
	ReceiveCode pgtype.Int4
}

func (q *Queries) InsertCargoRequest(ctx context.Context, arg InsertCargoRequestParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, insertCargoRequest,
		arg.ID,
		arg.ConsignerID,
		arg.RecipientID,
		arg.FromStation,
		arg.ToStation,
		arg.CreatedAt,
		arg.Deadline,
		arg.RouteID,
		arg.TripID,
		arg.Price,
		arg.Status,
		arg.ReceiveCode,
	)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const insertConsigner = `-- name: InsertConsigner :exec
INSERT INTO consigners (id) VALUES ($1)
`

func (q *Queries) InsertConsigner(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, insertConsigner, id)
	return err
}

const insertStation = `-- name: InsertStation :one
insert into stations (id, address, lat, lon) values ($1, $2, $3, $4) returning id
`

type InsertStationParams struct {
	ID      pgtype.UUID
	Address pgtype.Text
	Lat     pgtype.Float8
	Lon     pgtype.Float8
}

func (q *Queries) InsertStation(ctx context.Context, arg InsertStationParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, insertStation,
		arg.ID,
		arg.Address,
		arg.Lat,
		arg.Lon,
	)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const listCarsByOwner = `-- name: ListCarsByOwner :many
SELECT 
    id, type, length, width, height, max_weight, number, owner
FROM cars 
WHERE owner = $1 
ORDER BY id
`

func (q *Queries) ListCarsByOwner(ctx context.Context, owner pgtype.Int4) ([]Car, error) {
	rows, err := q.db.Query(ctx, listCarsByOwner, owner)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Car
	for rows.Next() {
		var i Car
		if err := rows.Scan(
			&i.ID,
			&i.Type,
			&i.Length,
			&i.Width,
			&i.Height,
			&i.MaxWeight,
			&i.Number,
			&i.Owner,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecipients = `-- name: ListRecipients :many
SELECT id, first_name, second_name, third_name, phone, email
FROM recipients
ORDER BY id
`

func (q *Queries) ListRecipients(ctx context.Context) ([]Recipient, error) {
	rows, err := q.db.Query(ctx, listRecipients)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Recipient
	for rows.Next() {
		var i Recipient
		if err := rows.Scan(
			&i.ID,
			&i.FirstName,
			&i.SecondName,
			&i.ThirdName,
			&i.Phone,
			&i.Email,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const selectStation = `-- name: SelectStation :one
select id, address, lat, lon from stations s where s.id = $1
`

func (q *Queries) SelectStation(ctx context.Context, id pgtype.UUID) (Station, error) {
	row := q.db.QueryRow(ctx, selectStation, id)
	var i Station
	err := row.Scan(
		&i.ID,
		&i.Address,
		&i.Lat,
		&i.Lon,
	)
	return i, err
}

const selectStations = `-- name: SelectStations :many
select id, address, lat, lon from stations s where s.id in ($1, $2)
`

type SelectStationsParams struct {
	ID   pgtype.UUID
	ID_2 pgtype.UUID
}

func (q *Queries) SelectStations(ctx context.Context, arg SelectStationsParams) ([]Station, error) {
	rows, err := q.db.Query(ctx, selectStations, arg.ID, arg.ID_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Station
	for rows.Next() {
		var i Station
		if err := rows.Scan(
			&i.ID,
			&i.Address,
			&i.Lat,
			&i.Lon,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCar = `-- name: UpdateCar :one
UPDATE cars 
SET 
    type = $2, 
    length = $3, 
    width = $4, 
    height = $5, 
    max_weight = $6, 
    number = $7, 
    owner = $8
WHERE id = $1 
RETURNING id
`

type UpdateCarParams struct {
	ID        int32
	Type      pgtype.Text
	Length    pgtype.Int4
	Width     pgtype.Int4
	Height    pgtype.Int4
	MaxWeight pgtype.Int4
	Number    pgtype.Text
	Owner     pgtype.Int4
}

func (q *Queries) UpdateCar(ctx context.Context, arg UpdateCarParams) (int32, error) {
	row := q.db.QueryRow(ctx, updateCar,
		arg.ID,
		arg.Type,
		arg.Length,
		arg.Width,
		arg.Height,
		arg.MaxWeight,
		arg.Number,
		arg.Owner,
	)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const updateCargoRequestTrip = `-- name: UpdateCargoRequestTrip :one
UPDATE cargo_requests 
SET trip_id = $2
WHERE id = $1 
RETURNING id
`

type UpdateCargoRequestTripParams struct {
	ID     pgtype.UUID
	TripID pgtype.UUID
}

func (q *Queries) UpdateCargoRequestTrip(ctx context.Context, arg UpdateCargoRequestTripParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, updateCargoRequestTrip, arg.ID, arg.TripID)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const updateCarrier = `-- name: UpdateCarrier :one
UPDATE carriers SET driver_category = $2 WHERE id = $1 RETURNING id
`

type UpdateCarrierParams struct {
	ID             int32
	DriverCategory pgtype.Text
}

func (q *Queries) UpdateCarrier(ctx context.Context, arg UpdateCarrierParams) (int32, error) {
	row := q.db.QueryRow(ctx, updateCarrier, arg.ID, arg.DriverCategory)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const updateRecipient = `-- name: UpdateRecipient :one
UPDATE recipients
SET first_name = $2,
    second_name = $3,
    third_name = $4,
    phone = $5,
    email = $6
WHERE id = $1
RETURNING id
`

type UpdateRecipientParams struct {
	ID         int32
	FirstName  pgtype.Text
	SecondName pgtype.Text
	ThirdName  pgtype.Text
	Phone      pgtype.Text
	Email      pgtype.Text
}

func (q *Queries) UpdateRecipient(ctx context.Context, arg UpdateRecipientParams) (int32, error) {
	row := q.db.QueryRow(ctx, updateRecipient,
		arg.ID,
		arg.FirstName,
		arg.SecondName,
		arg.ThirdName,
		arg.Phone,
		arg.Email,
	)
	var id int32
	err := row.Scan(&id)
	return id, err
}
