// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package pg

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createCarrier = `-- name: CreateCarrier :one
insert into carriers (driver_category) values ($1) returning id
`

func (q *Queries) CreateCarrier(ctx context.Context, driverCategory pgtype.Text) (int32, error) {
	row := q.db.QueryRow(ctx, createCarrier, driverCategory)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const getCarrier = `-- name: GetCarrier :one
select id, driver_category from carriers where id = $1
`

func (q *Queries) GetCarrier(ctx context.Context, id int32) (Carrier, error) {
	row := q.db.QueryRow(ctx, getCarrier, id)
	var i Carrier
	err := row.Scan(&i.ID, &i.DriverCategory)
	return i, err
}
