create table consigner (
    id int primary key generated by default as identity
);

create table carriers (
    id int primary key,
    driver_category varchar(50)
);

create table cars(
    id int primary key generated by default as identity,
    type varchar(10),
    length int,
    width int,
    height int,
    max_weight int,
    owner int references carriers(id)
);

create table trips(
    id uuid primary key default gen_random_uuid(),
    from_station bigint,
    to_station bigint,
    started_at timestamp,
    end_at timestamp,
    price decimal(10, 2),
    status varchar(50),
    carrier int references carriers(id),
    car int references cars(id)
);

create table stations_sequences(
    trip_id uuid references trips(id),
    station_id bigint,
    distance int,
    order_num int,
    primary key (trip_id, station_id)
);

create table requests(
    id uuid primary key default gen_random_uuid(),
    consigner_id int references consigner(id),
    created_at timestamp,
    deadline timestamp,
    trip_id uuid references trips(id),
    from_station bigint,
    to_station bigint,
    price decimal(10, 2),
    status varchar(50)
);

create table cargo (
    id uuid primary key default gen_random_uuid(),
    length int,
    width int,
    height int,
    weight int,
    is_glass bool,
    worth decimal(10, 2),
    request_id uuid references requests(id)
);
