// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package pg

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createCar = `-- name: CreateCar :one
INSERT INTO cars (
    type, length, width, height, max_weight, number, owner
) VALUES (
    $1, $2, $3, $4, $5, $6, $7
) RETURNING id
`

type CreateCarParams struct {
	Type      pgtype.Text
	Length    pgtype.Int4
	Width     pgtype.Int4
	Height    pgtype.Int4
	MaxWeight pgtype.Int4
	Number    pgtype.Text
	Owner     pgtype.Int4
}

func (q *Queries) CreateCar(ctx context.Context, arg CreateCarParams) (int32, error) {
	row := q.db.QueryRow(ctx, createCar,
		arg.Type,
		arg.Length,
		arg.Width,
		arg.Height,
		arg.MaxWeight,
		arg.Number,
		arg.Owner,
	)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const createCarrier = `-- name: CreateCarrier :one
INSERT INTO carriers (driver_category) VALUES ($1) RETURNING id
`

func (q *Queries) CreateCarrier(ctx context.Context, driverCategory pgtype.Text) (int32, error) {
	row := q.db.QueryRow(ctx, createCarrier, driverCategory)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const deleteCar = `-- name: DeleteCar :exec
DELETE FROM cars WHERE id = $1
`

func (q *Queries) DeleteCar(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteCar, id)
	return err
}

const deleteCarrier = `-- name: DeleteCarrier :exec
DELETE FROM carriers WHERE id = $1
`

func (q *Queries) DeleteCarrier(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteCarrier, id)
	return err
}

const getCar = `-- name: GetCar :one
SELECT 
    id, 
    type, 
    length, 
    width, 
    height, 
    max_weight, 
    number, 
    owner 
FROM cars 
WHERE id = $1
`

func (q *Queries) GetCar(ctx context.Context, id int32) (Car, error) {
	row := q.db.QueryRow(ctx, getCar, id)
	var i Car
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Length,
		&i.Width,
		&i.Height,
		&i.MaxWeight,
		&i.Number,
		&i.Owner,
	)
	return i, err
}

const getCarrier = `-- name: GetCarrier :one
SELECT id, driver_category FROM carriers WHERE id = $1
`

func (q *Queries) GetCarrier(ctx context.Context, id int32) (Carrier, error) {
	row := q.db.QueryRow(ctx, getCarrier, id)
	var i Carrier
	err := row.Scan(&i.ID, &i.DriverCategory)
	return i, err
}

const listCarsByOwner = `-- name: ListCarsByOwner :many
SELECT 
    id, type, length, width, height, max_weight, number, owner
FROM cars 
WHERE owner = $1 
ORDER BY id
`

func (q *Queries) ListCarsByOwner(ctx context.Context, owner pgtype.Int4) ([]Car, error) {
	rows, err := q.db.Query(ctx, listCarsByOwner, owner)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Car
	for rows.Next() {
		var i Car
		if err := rows.Scan(
			&i.ID,
			&i.Type,
			&i.Length,
			&i.Width,
			&i.Height,
			&i.MaxWeight,
			&i.Number,
			&i.Owner,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCar = `-- name: UpdateCar :one
UPDATE cars 
SET 
    type = $2, 
    length = $3, 
    width = $4, 
    height = $5, 
    max_weight = $6, 
    number = $7, 
    owner = $8
WHERE id = $1 
RETURNING id
`

type UpdateCarParams struct {
	ID        int32
	Type      pgtype.Text
	Length    pgtype.Int4
	Width     pgtype.Int4
	Height    pgtype.Int4
	MaxWeight pgtype.Int4
	Number    pgtype.Text
	Owner     pgtype.Int4
}

func (q *Queries) UpdateCar(ctx context.Context, arg UpdateCarParams) (int32, error) {
	row := q.db.QueryRow(ctx, updateCar,
		arg.ID,
		arg.Type,
		arg.Length,
		arg.Width,
		arg.Height,
		arg.MaxWeight,
		arg.Number,
		arg.Owner,
	)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const updateCarrier = `-- name: UpdateCarrier :one
UPDATE carriers SET driver_category = $2 WHERE id = $1 RETURNING id
`

type UpdateCarrierParams struct {
	ID             int32
	DriverCategory pgtype.Text
}

func (q *Queries) UpdateCarrier(ctx context.Context, arg UpdateCarrierParams) (int32, error) {
	row := q.db.QueryRow(ctx, updateCarrier, arg.ID, arg.DriverCategory)
	var id int32
	err := row.Scan(&id)
	return id, err
}
